APP_DIR=$${BUILD_ROOT_DIR}
LIB_DIR=$${BUILD_ROOT_DIR}/lib
PLUGINS_DIR=$${BUILD_ROOT_DIR}/plugins

INTERFACE_SRC_NAME=interface
INTERFACE_LIB_NAME=PluginInterface

INCLUDEPATH += $${SRC_ROOT_DIR}/plugins/$${INTERFACE_SRC_NAME}
DEPENDPATH += $${SRC_ROOT_DIR}/plugins/$${INTERFACE_SRC_NAME}
